const horseImage='https://www.publicdomainpictures.net/pictures/280000/velka/standing-horse.jpg';
const STORAGE='equicare_v3';
const LEGACY='eqrel';

function uid(){return 'id_'+Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function todayISO(){return new Date().toISOString().slice(0,10)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ageFromBirth(birth){if(!birth)return '';const d=new Date(birth);if(Number.isNaN(d.getTime()))return '';const n=new Date();let a=n.getFullYear()-d.getFullYear();const m=n.getMonth()-d.getMonth();if(m<0||(m===0&&n.getDate()<d.getDate()))a--;return Math.max(0,a)}
function duration(a,b){if(!a||!b)return '—';const A=a.split(':').map(Number),B=b.split(':').map(Number);let m=B[0]*60+B[1]-A[0]*60-A[1];if(m<0)m+=1440;return `${Math.floor(m/60)} h ${m%60} min`}
function sevLabel(s=0){return ['Kein','Leicht','Stark','Extrem'][Number(s)||0]}
function sevClass(s=0){return 's'+(Number(s)||0)}

function blankHorse(data={}){
  return {
    id:data.id||uid(),
    name:data.name||'',race:data.race||'',birth:data.birth||'',age:data.age??'',sex:data.sex||'',color:data.color||'',height:data.height||'',weight:data.weight||'',chip:data.chip||'',passport:data.passport||'',notes:data.notes||'',
    daily:Array.isArray(data.daily)?data.daily:[],
    zones:data.zones||{},
    meds:Array.isArray(data.meds)?data.meds:[],
    feed:Array.isArray(data.feed)?data.feed:[],
    treatments:Array.isArray(data.treatments)?data.treatments:(Array.isArray(data.treat)?data.treat:[]),
    housing:Array.isArray(data.housing)?data.housing:[]
  }
}
function seedHorse(){
  return blankHorse({id:'bella',name:'Bella',race:'PRE',birth:'2014-05-12',age:12,sex:'Stute',color:'Schimmel',height:'164 cm',weight:'580 kg',chip:'DE 456789123456789',passport:'DE 987654321',daily:[
    {date:'2026-08-15',itch:5,insects:'Mittel',start:'07:45',end:'15:00',blanket:'Ekzemdecke',temp:24,hum:65},
    {date:'2026-08-16',itch:4,insects:'Mittel',start:'08:00',end:'14:40',blanket:'Ekzemdecke',temp:23,hum:68},
    {date:'2026-08-17',itch:6,insects:'Stark',start:'07:45',end:'15:20',blanket:'Ekzemdecke',temp:26,hum:64},
    {date:'2026-08-18',itch:7,insects:'Stark',start:'07:30',end:'15:35',blanket:'Keine Decke',temp:27,hum:63},
    {date:'2026-08-19',itch:8,insects:'Extrem',start:'07:45',end:'15:25',blanket:'Ekzemdecke',temp:28,hum:64},
    {date:'2026-08-20',itch:9,insects:'Stark',start:'07:45',end:'15:20',blanket:'Ekzemdecke',temp:27,hum:64,note:'Mähnenkamm stark gescheuert.'}
  ],zones:{Mähnenkamm:{s:3,n:'Stark gescheuert nach dem Weidegang.',sy:['Fell abgerieben','Schuppen','Krusten','Rötung']},Hals:{s:1},Rücken:{s:0},Rumpf:{s:0},Bauch:{s:1},Kruppe:{s:2},Schweifrübe:{s:3},Vorderbein:{s:0},Hinterbein:{s:0}},meds:[{id:uid(),name:'Cetirizin 10 mg',dose:'3 Tabletten morgens / 3 Tabletten abends',reason:'Sommerekzem / Juckreiz',am:true,pm:false}],feed:[['Raufutter','Heu','10,0 kg'],['Kraftfutter','AlpenGrün Müsli','200 g'],['Zusatzfutter','Zink','30 g'],['Zusatzfutter','Hanföl','25 ml'],['Zusatzfutter','Mineralfutter','100 g']],treatments:[['20.08. 18:25','Mähnenkamm','Hautlotion XY','20 ml']],housing:['Offenstall','Weide']})
}

function loadState(){
  try{const v=JSON.parse(localStorage.getItem(STORAGE)||'null');if(v&&Array.isArray(v.horses)&&v.horses.length)return v}catch(e){}
  try{
    const old=JSON.parse(localStorage.getItem(LEGACY)||'null');
    if(old&&old.horse){
      const h=blankHorse({...old.horse,id:'bella',daily:old.daily,zones:old.zones,meds:old.meds,feed:old.feed,treatments:old.treat,housing:old.housing});
      return {version:3,activeHorseId:h.id,horses:[h]};
    }
  }catch(e){}
  const h=seedHorse();return {version:3,activeHorseId:h.id,horses:[h]}
}
let S=loadState();
let R='today',stack=[],zone='Mähnenkamm';
const root=document.getElementById('root');
const modal=document.getElementById('modal');
const toast=document.getElementById('toast');

function save(){localStorage.setItem(STORAGE,JSON.stringify(S))}
function activeHorse(){let h=S.horses.find(x=>x.id===S.activeHorseId);if(!h){h=S.horses[0];if(h)S.activeHorseId=h.id}return h}
function lastDaily(h=activeHorse()){
  if(!h)return null;
  if(!h.daily.length) return {date:todayISO(),itch:0,insects:'Keine',start:'',end:'',blanket:'Keine Decke',temp:'',hum:'',note:''};
  return h.daily[h.daily.length-1];
}
function note(x){toast.textContent=x;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1500)}
function go(r,push=true){if(push&&R!==r)stack.push(R);R=r;render();window.scrollTo({top:0,behavior:'smooth'})}
function back(){R=stack.pop()||'today';render();window.scrollTo(0,0)}
function selectHorse(id){S.activeHorseId=id;save();note('Pferd ausgewählt');go('profile',false)}

function render(){document.querySelectorAll('.nav [data-r]').forEach(b=>b.classList.toggle('on',b.dataset.r===R));root.innerHTML=(screens[R]||screens.today)();wire()}

const screens={
  today(){const h=activeHorse();if(!h)return emptyState();const d=lastDaily(h);return `<div class="row between"><div class="row"><div class="avatar">🐴</div><div><b>${esc(h.name||'Pferd')}⌄</b><div class="sub">${esc(d.date||todayISO())}</div></div></div><span class="badge">Heute</span></div><div class="card"><b>Juckreiz heute</b><div class="itch">${Array.from({length:11},(_,i)=>`<button data-itch="${i}" class="${Number(d.itch)===i?'on':''}">${i}</button>`).join('')}</div></div><div class="grid"><div class="metric"><small>🪰 Insekten</small><b>${esc(d.insects||'—')}</b><div class="sub">heutige Belastung</div></div><div class="metric"><small>🌤 Wetter</small><b>${d.temp!==''?esc(d.temp)+' °C':'—'}</b><div class="sub">${d.hum!==''?esc(d.hum)+'% Luftfeuchte':'nicht eingetragen'}</div></div><div class="metric"><small>🌿 Weide</small><b>${duration(d.start,d.end)}</b><div class="sub">${esc(d.start||'—')} – ${esc(d.end||'—')}</div></div><div class="metric"><small>🧥 Schutz</small><b>${esc(d.blanket||'—')}</b><div class="sub">heute dokumentiert</div></div><div class="metric"><small>💊 Medikamente</small><b>${h.meds.filter(m=>!(m.am&&m.pm)).length} offen</b><div class="sub">Gabeprotokoll</div></div><div class="metric"><small>🥕 Fütterung</small><b>${h.feed.length} Einträge</b><div class="sub">aktueller Plan</div></div></div><button class="btn primary full" style="margin-top:9px" onclick="go('quick')">＋ Neuer Eintrag</button>`},
  horses(){return `<div class="title">Meine Pferde</div><div class="list">${S.horses.map(h=>`<button class="item" onclick="selectHorse('${h.id}')"><div class="avatar">🐴</div><div style="min-width:0"><b>${esc(h.name||'Ohne Namen')}</b><div class="sub">${esc(displayAge(h))}${h.race?' · '+esc(h.race):''}${h.sex?' · '+esc(h.sex):''}</div></div>${h.id===S.activeHorseId?'<span class="badge">Aktiv</span>':''}<span class="chev">›</span></button>`).join('')}</div><button class="btn primary full" style="margin-top:10px" onclick="horseSheet()">＋ Pferd hinzufügen</button>`},
  profile(){const h=activeHorse();if(!h)return emptyState();return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">${esc(h.name)}</div><span></span></div><div class="card" style="text-align:center"><div class="avatar" style="margin:auto;width:80px;height:80px;font-size:40px">🐴</div><b style="display:block;margin-top:7px">${esc(h.name)}</b><div class="sub">${esc(h.race||'Rasse offen')}${h.sex?' · '+esc(h.sex):''}</div></div><div class="tabs"><button class="tab on">Profil</button><button class="tab">Gesundheit</button><button class="tab">Kontakte</button><button class="tab">Notizen</button></div><div class="card"><b>Stammdaten</b><div class="detail">${detailRows(h)}</div></div><div class="actions"><button class="btn primary" onclick="editHorse()">Bearbeiten</button><button class="btn outline" onclick="deleteHorsePrompt()">Pferd löschen</button></div>`},
  map(){const h=activeHorse();if(!h)return emptyState();return `<div class="top"><button class="back" onclick="back()">‹</button><div><div class="title">Interaktive Pferdekarte</div><div class="sub">${esc(h.name)} · Linke Seite</div></div><button class="btn primary" onclick="save();note('Körperkarte gespeichert')">Speichern</button></div><div class="mapbox"><div class="map"><img src="${horseImage}"><svg viewBox="0 0 1000 1000">${Z('Kopf','80,300 160,235 230,260 245,335 190,390 100,370')}${Z('Mähnenkamm','200,240 275,250 400,345 420,405 360,420 280,350')}${Z('Hals','230,310 315,330 405,400 355,520 285,520 230,430')}${Z('Brust','280,470 355,455 370,620 300,640 255,550')}${Z('Rücken','365,390 530,400 710,390 790,420 770,475 580,475 430,460')}${Z('Rumpf','350,445 450,425 610,435 770,435 790,590 710,650 550,665 405,620 350,560')}${Z('Bauch','395,610 550,665 710,650 670,720 525,740 410,710')}${Z('Kruppe','710,410 795,400 850,455 845,585 790,635 730,615 775,555 765,445')}${Z('Schweifrübe','820,395 875,405 910,435 880,470 830,450')}${Z('Vorderbein','300,600 360,600 350,920 305,945 280,920')}${Z('Hinterbein','735,600 795,590 825,905 790,940 755,905')}</svg></div><div class="views">${['Links','Rechts','Vorne','Hinten','Oben'].map((v,i)=>`<button class="${i===0?'on':''}" onclick="note('${v} ausgewählt')">${i<2?'♞':'♟'}<br>${v}</button>`).join('')}</div><div class="legend"><span><i class="dot g"></i>Kein Juckreiz</span><span><i class="dot y"></i>Leicht</span><span><i class="dot o"></i>Stark</span><span><i class="dot r"></i>Extrem</span></div></div><div class="card row between"><div><b>${esc(zone)}</b><div class="sub">${sevLabel((h.zones[zone]||{}).s)}</div></div><button class="btn soft" onclick="go('zone')">Bearbeiten</button></div>`},
  zone(){const h=activeHorse(),z=h.zones[zone]||{s:0,n:'',sy:[]},sym=['Fell abgerieben','Schuppen','Krusten','Rötung','Offene Wunde','Nässend'];return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">${esc(zone)}</div><span></span></div><div class="card"><b>Wie stark ist der Juckreiz?</b><div class="sev" style="margin-top:10px">${[0,1,2,3].map(i=>`<button data-sev="${i}" class="${Number(z.s)===i?'on':''}"><span class="sdot ${['g','y','o','r'][i]}"></span>${sevLabel(i)}</button>`).join('')}</div></div><div class="card"><b>Symptome</b><div class="checks" style="margin-top:10px">${sym.map(s=>`<label><input type="checkbox" data-sym="${esc(s)}" ${(z.sy||[]).includes(s)?'checked':''}> ${esc(s)}</label>`).join('')}</div><div class="field"><label>Notiz</label><textarea id="znote">${esc(z.n||'')}</textarea></div></div><button class="btn primary full" id="saveZone">Speichern</button>`},
  quick(){const d=lastDaily();return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">Tagesprotokoll</div><span></span></div><div class="card"><div class="field"><label>Datum</label><input id="qd" type="date" value="${esc(d.date||todayISO())}"></div><div class="field"><label>Juckreiz <b id="qo">${Number(d.itch)||0}</b>/10</label><input id="qi" type="range" min="0" max="10" value="${Number(d.itch)||0}"></div><div class="split"><div class="field"><label>Insekten</label><select id="qin">${['Keine','Gering','Mittel','Stark','Extrem'].map(x=>`<option ${x===d.insects?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Schutz</label><select id="qb">${['Keine Decke','Ekzemdecke','Fliegendecke','Fliegenmaske + Decke'].map(x=>`<option ${x===d.blanket?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="split"><div class="field"><label>Weide Start</label><input id="qs" type="time" value="${esc(d.start||'')}"></div><div class="field"><label>Weide Ende</label><input id="qe" type="time" value="${esc(d.end||'')}"></div></div><div class="split"><div class="field"><label>Temperatur °C</label><input id="qt" type="number" inputmode="decimal" value="${esc(d.temp??'')}"></div><div class="field"><label>Luftfeuchte %</label><input id="qh" type="number" inputmode="numeric" value="${esc(d.hum??'')}"></div></div><div class="field"><label>Notiz</label><textarea id="qn">${esc(d.note||'')}</textarea></div></div><button class="btn primary full" id="saveDaily">Speichern</button>`},
  history(){const a=activeHorse().daily,w=360,h=210,p=10;if(!a.length)return `<div class="title">Verlauf</div><div class="card">Noch keine Tagesdaten vorhanden.</div>`;const pts=a.map((d,i)=>`${p+i*(w-2*p)/Math.max(1,a.length-1)},${h-p-(Number(d.itch)||0)/10*(h-2*p)}`).join(' ');return `<div class="title">Verlauf</div><div class="chips"><button class="chip on">Juckreiz</button><button class="chip">Temperatur</button><button class="chip">Insekten</button><button class="chip">Weide</button></div><div class="card"><div class="chart"><svg viewBox="0 0 ${w} ${h}"><polyline points="${pts}" fill="none" stroke="#e63b40" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg></div></div>`},
  meds(){const h=activeHorse();return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">Medikamente</div><button class="back" onclick="medSheet()">＋</button></div>${h.meds.length?h.meds.map(m=>`<div class="med"><div class="row between"><b>${esc(m.name)}</b><span class="badge">Aktiv</span></div><div class="sub" style="margin-top:8px">${esc(m.dose)}</div><div class="sub">${esc(m.reason)}</div><div class="split" style="margin-top:10px"><button class="btn ${m.am?'soft':'outline'}" onclick="toggleMed('${m.id}','am')">${m.am?'✓':'○'} morgens</button><button class="btn ${m.pm?'soft':'outline'}" onclick="toggleMed('${m.id}','pm')">${m.pm?'✓':'○'} abends</button></div></div>`).join(''):'<div class="card">Noch keine Medikamente angelegt.</div>'}`},
  feed(){const h=activeHorse();return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">Fütterungsplan</div><button class="back" onclick="feedSheet()">＋</button></div>${['Raufutter','Kraftfutter','Zusatzfutter'].map(g=>`<div class="feed"><b>${g}</b>${h.feed.filter(x=>x[0]===g).map(x=>`<div class="drow"><span>${esc(x[1])}</span><span>${esc(x[2])}</span></div>`).join('')}<button class="btn soft full" style="margin-top:8px" onclick="feedSheet('${g}')">＋ hinzufügen</button></div>`).join('')}`},
  pasture(){const h=activeHorse(),d=lastDaily(h);return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">Weide & Haltung</div><span></span></div><div class="card"><b>Haltung</b><div class="housing" style="margin-top:10px">${['Box','Offenstall','Paddock','Weide'].map(x=>`<button data-house="${x}" class="${h.housing.includes(x)?'on':''}">${x}</button>`).join('')}</div><div class="split"><div class="field"><label>Start</label><input id="ps" type="time" value="${esc(d.start||'')}"></div><div class="field"><label>Ende</label><input id="pe" type="time" value="${esc(d.end||'')}"></div></div><div class="field"><label>Notiz</label><textarea id="pn">${esc(d.pastureNote||'')}</textarea></div></div><button class="btn primary full" id="savePasture">Speichern</button>`},
  treatment(){const h=activeHorse();return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">Behandlungen</div><button class="back" onclick="treatmentSheet()">＋</button></div>${h.treatments.length?h.treatments.map(t=>`<div class="card"><b>${esc(t[1]||'Behandlung')}</b><div class="sub">${esc(t[0]||'')}</div><div style="margin-top:8px">${esc(t[2]||'')} ${t[3]?'· '+esc(t[3]):''}</div></div>`).join(''):'<div class="card">Noch keine Behandlung dokumentiert.</div>'}`},
  calendar(){const h=activeHorse(),days=new Map(h.daily.map(d=>[Number(String(d.date).slice(-2)),Math.min(3,Math.floor((Number(d.itch)||0)/3))]));return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">Kalender</div><span></span></div><div class="week"><span>Mo</span><span>Di</span><span>Mi</span><span>Do</span><span>Fr</span><span>Sa</span><span>So</span></div><div class="cal">${Array.from({length:35},(_,i)=>{const d=i-4;if(d<1||d>31)return '<span></span>';return `<button class="day ${sevClass(days.get(d)||0)}">${d}</button>`}).join('')}</div>`},
  report(){const h=activeHorse(),a=h.daily;if(!a.length)return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">Monatsbericht</div><span></span></div><div class="card">Noch keine Daten für eine Auswertung.</div>`;const avg=(a.reduce((s,d)=>s+(Number(d.itch)||0),0)/a.length).toFixed(1);return `<div class="top"><button class="back" onclick="back()">‹</button><div class="title">Monatsbericht</div><span></span></div><div class="card"><div class="sub">Durchschnittlicher Juckreiz</div><div style="font-size:32px;font-weight:800">${avg}<span style="font-size:14px"> / 10</span></div></div><div class="card"><b>${esc(h.name)}</b><div class="drow"><span>Tagesprotokolle</span><span>${a.length}</span></div><div class="drow"><span>Medikamente</span><span>${h.meds.length}</span></div><div class="drow"><span>Futtereinträge</span><span>${h.feed.length}</span></div><div class="drow"><span>Behandlungen</span><span>${h.treatments.length}</span></div></div>`},
  more(){return `<div class="title">Mehr</div><div class="more"><button onclick="go('map')"><i>🐴</i><b>Körperkarte</b></button><button onclick="go('treatment')"><i>🧴</i><b>Behandlungen</b></button><button onclick="go('meds')"><i>💊</i><b>Medikamente</b></button><button onclick="go('feed')"><i>🥕</i><b>Fütterung</b></button><button onclick="go('pasture')"><i>🌿</i><b>Weide & Haltung</b></button><button onclick="go('calendar')"><i>📅</i><b>Kalender</b></button><button onclick="go('report')"><i>📊</i><b>Monatsbericht</b></button><button onclick="go('profile')"><i>🪪</i><b>Pferdeprofil</b></button></div>`}
};

function emptyState(){return `<div class="card"><b>Noch kein Pferd angelegt.</b><div class="sub" style="margin:8px 0 12px">Lege zuerst ein Pferd mit seinen Stammdaten an.</div><button class="btn primary full" onclick="horseSheet()">＋ Pferd hinzufügen</button></div>`}
function displayAge(h){const a=h.age!==''&&h.age!=null?h.age:ageFromBirth(h.birth);return a!==''?`${a} Jahre`:'Alter offen'}
function detailRows(h){const rows=[['Geburtsdatum',h.birth||'—'],['Alter',displayAge(h)],['Rasse',h.race||'—'],['Geschlecht',h.sex||'—'],['Farbe',h.color||'—'],['Stockmaß',h.height||'—'],['Gewicht',h.weight||'—'],['Chipnummer',h.chip||'—'],['Equidenpass',h.passport||'—']];return rows.map(x=>`<div class="drow"><span>${x[0]}</span><span>${esc(x[1])}</span></div>`).join('')}
function Z(name,points){const h=activeHorse(),s=(h.zones[name]||{}).s||0;return `<polygon class="z ${sevClass(s)} ${zone===name?'sel':''}" data-zone="${name}" points="${points}"/>`}

function wire(){document.querySelectorAll('.nav [data-r]').forEach(b=>b.onclick=()=>go(b.dataset.r));root.querySelectorAll('[data-itch]').forEach(b=>b.onclick=()=>{const h=activeHorse(),d=lastDaily(h);d.itch=Number(b.dataset.itch);const idx=h.daily.findIndex(x=>x.date===d.date);if(idx<0)h.daily.push(d);save();render();note('Juckreiz gespeichert')});root.querySelectorAll('[data-zone]').forEach(el=>el.onclick=()=>{zone=el.dataset.zone;go('zone')});root.querySelectorAll('[data-sev]').forEach(b=>b.onclick=()=>{root.querySelectorAll('[data-sev]').forEach(x=>x.classList.remove('on'));b.classList.add('on')});const qi=document.getElementById('qi'),qo=document.getElementById('qo');if(qi&&qo)qi.oninput=()=>qo.textContent=qi.value;const sd=document.getElementById('saveDaily');if(sd)sd.onclick=saveDaily;const sz=document.getElementById('saveZone');if(sz)sz.onclick=saveZone;root.querySelectorAll('[data-house]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));const sp=document.getElementById('savePasture');if(sp)sp.onclick=savePasture}
function saveDaily(){const h=activeHorse();const obj={date:qd.value||todayISO(),itch:Number(qi.value),insects:qin.value,start:qs.value,end:qe.value,blanket:qb.value,temp:qt.value===''?'':Number(qt.value),hum:qh.value===''?'':Number(qh.value),note:qn.value};const idx=h.daily.findIndex(x=>x.date===obj.date);if(idx>=0)h.daily[idx]={...h.daily[idx],...obj};else h.daily.push(obj);h.daily.sort((a,b)=>a.date.localeCompare(b.date));save();note('Tagesprotokoll gespeichert');go('today',false)}
function saveZone(){const h=activeHorse();const s=Number(root.querySelector('[data-sev].on')?.dataset.sev||0);const sy=[...root.querySelectorAll('[data-sym]:checked')].map(x=>x.dataset.sym);h.zones[zone]={s,sy,n:document.getElementById('znote').value};save();note('Körperbereich gespeichert');back()}
function savePasture(){const h=activeHorse();h.housing=[...root.querySelectorAll('[data-house].on')].map(x=>x.dataset.house);const d=lastDaily(h);const obj={...d,start:ps.value,end:pe.value,pastureNote:pn.value};const idx=h.daily.findIndex(x=>x.date===obj.date);if(idx>=0)h.daily[idx]=obj;else h.daily.push(obj);save();note('Weide & Haltung gespeichert');go('today',false)}
function toggleMed(id,key){const m=activeHorse().meds.find(x=>x.id===id);if(m){m[key]=!m[key];save();render()}}

function openSheet(title,body,saveText='Speichern',onSave=''){modal.innerHTML=`<div class="sheetbg" onclick="if(event.target===this)closeSheet()"><div class="sheet"><div class="row between"><h2>${title}</h2><button class="back" onclick="closeSheet()">×</button></div>${body}<div class="actions"><button class="btn outline" onclick="closeSheet()">Abbrechen</button><button class="btn primary" ${onSave?`onclick="${onSave}"`:''}>${saveText}</button></div></div></div>`}
function closeSheet(){modal.innerHTML=''}
function horseFields(h={}){return `<div><div class="field"><label>Name *</label><input id="hn" autocomplete="off" value="${esc(h.name||'')}" placeholder="z. B. Bella"></div><div class="field"><label>Rasse *</label><input id="hr" autocomplete="off" value="${esc(h.race||'')}" placeholder="z. B. PRE"></div><div class="split"><div class="field"><label>Geburtsdatum</label><input id="hb" type="date" value="${esc(normalizeBirth(h.birth))}"></div><div class="field"><label>Alter</label><input id="ha" type="number" min="0" max="60" inputmode="numeric" value="${h.age??''}" placeholder="12"></div></div><div class="split"><div class="field"><label>Geschlecht</label><select id="hs"><option value="">Bitte wählen</option>${['Stute','Wallach','Hengst'].map(x=>`<option ${h.sex===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Farbe</label><input id="hc" value="${esc(h.color||'')}" placeholder="z. B. Schimmel"></div></div><div class="split"><div class="field"><label>Stockmaß</label><input id="hh" value="${esc(h.height||'')}" placeholder="z. B. 164 cm"></div><div class="field"><label>Gewicht</label><input id="hw" value="${esc(h.weight||'')}" placeholder="z. B. 580 kg"></div></div><div class="field"><label>Chipnummer</label><input id="hchip" value="${esc(h.chip||'')}"></div><div class="field"><label>Equidenpass</label><input id="hpass" value="${esc(h.passport||'')}"></div><div class="field"><label>Notizen</label><textarea id="hnotes" placeholder="Besonderheiten, Erkrankungen, Allergien …">${esc(h.notes||'')}</textarea></div></div>`}
function normalizeBirth(v=''){if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=String(v).match(/^(\d{2})\.(\d{2})\.(\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:''}
function readHorseForm(){return {name:hn.value.trim(),race:hr.value.trim(),birth:hb.value,age:ha.value===''?(hb.value?ageFromBirth(hb.value):''):Number(ha.value),sex:hs.value,color:hc.value.trim(),height:hh.value.trim(),weight:hw.value.trim(),chip:hchip.value.trim(),passport:hpass.value.trim(),notes:hnotes.value.trim()}}
function horseSheet(){openSheet('Pferd hinzufügen',horseFields(),'Pferd speichern','saveNewHorse()')}
function saveNewHorse(){const v=readHorseForm();if(!v.name){note('Bitte Name eingeben');hn.focus();return}if(!v.race){note('Bitte Rasse eingeben');hr.focus();return}const h=blankHorse(v);S.horses.push(h);S.activeHorseId=h.id;save();closeSheet();note('Pferd gespeichert');go('profile',false)}
function editHorse(){const h=activeHorse();openSheet('Pferd bearbeiten',horseFields(h),'Änderungen speichern','saveHorseEdit()')}
function saveHorseEdit(){const h=activeHorse(),v=readHorseForm();if(!v.name){note('Bitte Name eingeben');return}Object.assign(h,v);save();closeSheet();note('Pferdeprofil gespeichert');render()}
function deleteHorsePrompt(){const h=activeHorse();if(!h)return;if(!confirm(`${h.name} wirklich löschen?`))return;S.horses=S.horses.filter(x=>x.id!==h.id);S.activeHorseId=S.horses[0]?.id||null;save();note('Pferd gelöscht');go('horses',false)}
function medSheet(){openSheet('Medikament hinzufügen',`<div class="field"><label>Name *</label><input id="mn"></div><div class="field"><label>Dosierung</label><input id="md"></div><div class="field"><label>Grund</label><input id="mr"></div>`,'Medikament speichern','saveMed()')}
function saveMed(){if(!mn.value.trim()){note('Bitte Medikament eingeben');return}activeHorse().meds.push({id:uid(),name:mn.value.trim(),dose:md.value.trim(),reason:mr.value.trim(),am:false,pm:false});save();closeSheet();note('Medikament gespeichert');render()}
function feedSheet(group='Raufutter'){openSheet('Futter hinzufügen',`<div class="field"><label>Kategorie</label><select id="fg">${['Raufutter','Kraftfutter','Zusatzfutter'].map(x=>`<option ${x===group?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Futter *</label><input id="fn"></div><div class="field"><label>Menge</label><input id="fa" placeholder="z. B. 200 g"></div>`,'Futter speichern','saveFeed()')}
function saveFeed(){if(!fn.value.trim()){note('Bitte Futter eingeben');return}activeHorse().feed.push([fg.value,fn.value.trim(),fa.value.trim()]);save();closeSheet();note('Futter gespeichert');render()}
function treatmentSheet(){openSheet('Behandlung hinzufügen',`<div class="field"><label>Bereich</label><input id="ta" value="Mähnenkamm"></div><div class="field"><label>Produkt / Behandlung *</label><input id="tp"></div><div class="field"><label>Menge / Anwendung</label><input id="td"></div>`,'Behandlung speichern','saveTreatment()')}
function saveTreatment(){if(!tp.value.trim()){note('Bitte Behandlung eingeben');return}const d=new Date();const stamp=d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})+' '+d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});activeHorse().treatments.unshift([stamp,ta.value.trim(),tp.value.trim(),td.value.trim()]);save();closeSheet();note('Behandlung gespeichert');render()}

render();